[package]
name = "llm-rs"
version = "0.0.0"
edition.workspace = true
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
tensor.path = "../tensor"

digit-layout = "0.3"
mem-rearrange = "0.1"
itertools = "0.14"
gemm = "0.18"

memmap2 = "0.9"
globset = "0.4"
rand = "0.9"
